apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: feature-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "<REPLACE_WITH_YOUR_GIT_URL>"
    path: gitops/modules/feature
  destination:
    server: https://kubernetes.default.svc
    namespace: feature
  syncPolicy:
    automated: {}
