apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messaging-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "<REPLACE_WITH_YOUR_GIT_URL>"
    path: gitops/modules/messaging
  destination:
    server: https://kubernetes.default.svc
    namespace: messaging
  syncPolicy:
    automated: {}
