apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pop-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dullbrowny/pop-poc
    path: gitops/argocd-apps.yaml
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

