apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metadata-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "<REPLACE_WITH_YOUR_GIT_URL>"
    path: gitops/core/metadata
  destination:
    server: https://kubernetes.default.svc
    namespace: metadata
  syncPolicy:
    automated: {}
