apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "<REPLACE_WITH_YOUR_GIT_URL>"
    path: gitops/core/policy/manifests
    directory:
      recurse: true  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
