apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlas
  namespace: argocd
spec:
  project: default

  # point at your local manifests instead of a non-existent Helm chart
  source:
    repoURL: "https://github.com/dullbrowny/pop-poc"
    path: "gitops/core/atlas"
    directory:
      recurse: true

  destination:
    server: "https://kubernetes.default.svc"
    namespace: metadata

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

