apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlas
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/dullbrowny/pop-poc"
    chart: apache-atlas
    repoURL: "https://spanda-repo.example.com/helm-charts" # replace with your chart repo
    targetRevision: "2.3.0"
    helm:
      values: |
        image:
          repository: sburn/apache-atlas
          tag: "2.3.0"
  destination:
    server: https://kubernetes.default.svc
    namespace: metadata
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

