apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlas
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: apache-atlas
    targetRevision: "5.0.0"
    helm:
      values: |
        image:
          registry: docker.io
          repository: bitnami/apache-atlas
          tag: "2.3.0-debian-10-r0"
  destination:
    server: https://kubernetes.default.svc
    namespace: metadata
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

