apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas
  namespace: metadata
spec:
  replicas: 1
  selector:
    matchLabels: { app: atlas }
  template:
    metadata: { labels: { app: atlas } }
    spec:
      containers:
      - name: atlas
        image: bitnami/apache-atlas:2.3.0-debian-10-r0
        ports:
        - containerPort: 21000

