apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas
  namespace: metadata
  labels:
    app: atlas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlas
  template:
    metadata:
      labels:
        app: atlas
    spec:
      containers:
      - name: atlas
        image: sburn/apache-atlas:2.3.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 21000

