apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas
  namespace: metadata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlas
  template:
    metadata:
      labels:
        app: atlas
    spec:
      containers:
        - name: atlas
          # use the official Apache Atlas image
          image: apache/atlas:2.3.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 21000

